server:
  port: 8763

spring:
  cloud:
    gateway:
      routes:
        - id: demo
          uri: http://apigw.easy2easiest.com:8433
          predicates:
            - Path=/test/ratelimit
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@userKeyResolver}"